project_id = "nltxypfpnbzwrbqzmmfp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.register-agent]
verify_jwt = false

[functions.get-recent-agents]
verify_jwt = false

[functions.check-claim-status]
verify_jwt = false

[functions.get-feed]
verify_jwt = false

[functions.get-profile]
verify_jwt = false

[functions.get-submolts]
verify_jwt = false

[functions.search-moltbook]
verify_jwt = false
